- hosts: all
  vars:
    domainname: "{{ inventory_hostname | regex_replace('^[^.]*.', '') }}"
  connection: local
  gather_facts: no

  pre_tasks:
    - name: Gathering System Inventory Info
      redfish_info:
        category: Systems
        command: GetSystemInventory
        baseuri: "{{ idrac_ip }}"
        username: "{{ idrac_username }}"
        password: "{{ idrac_password }}"
      register: redfish_info

  tasks:
    - name: Install ESXi
      block:
        - name: Create temp directory for kickstart file
          file:
            path: "{{ playbook_dir }}/tmp/{{ inventory_hostname }}"
            state: directory

        - name: Creating kickstart file with proper automation content
          copy:
            force: true
            dest: "{{ playbook_dir }}/tmp/{{ inventory_hostname }}/ks.cfg"
            content: |
              vmaccepteula
              rootpw VMware123!
              clearpart --firstdisk="DELL BOSS-N1" --overwritevmfs
              install --firstdisk="DELL BOSS-N1" --overwritevmfs
              network --device=vmnic0 --bootproto=static --vlanid={{ networks['mgmt']['vlan'] }} --ip={{ mgmt_ip }} --netmask={{ networks['mgmt']['network']['subnet_mask'] }} --gateway={{ networks['mgmt']['network']['default_gateway'] }} --nameserver="{{ dns_servers[0] }},{{ dns_servers[1] }}" --hostname="{{ inventory_hostname }}"
              reboot

        - name: Create custom ESXi install ISO
          shell: >
            xorriso
            -indev "{{ playbook_dir }}/iso/ESXI8-U3.iso"
            -outdev "{{ playbook_dir }}/{{ inventory_hostname.split('.')[0] }}.iso"
            -boot_image any keep
            -update "{{ playbook_dir }}/files/boot.cfg" /BOOT.CFG
            -update "{{ playbook_dir }}/files/boot.cfg" /EFI/BOOT/BOOT.CFG
            -update "{{ playbook_dir }}/tmp/{{ inventory_hostname }}/ks.cfg" /KS.CFG

        - name: Boot to Network ISO 
          dellemc.openmanage.idrac_os_deployment:
            validate_certs: false
            idrac_ip: "{{ idrac_ip }}"
            idrac_user: "{{ idrac_username }}"
            idrac_password: "{{ idrac_password }}"
            share_name: "192.168.170.254:/volume3/Infra-Test/baremetalesxi"
            iso_image: "{{ inventory_hostname.split('.')[0] }}.iso"
            expose_duration: 10
          delegate_to: localhost

        - name: Delete temp directory for kickstart file
          file:
            path: "{{ playbook_dir }}/tmp/{{ inventory_hostname }}"
            state: absent

        - name: Delete custom ESXi install ISO
          file:
            path: "{{ playbook_dir }}/{{ inventory_hostname.split('.')[0] }}.iso"
            state: absent
